version: '3'

services:
  apigateway:
    container_name: apigateway
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - apigateway-network
    ports:
      - 8080:8080

networks:
  apigateway-network:
    name: apigateway-network