version: '3'

services:
  apigaeway:
    container_name: apigateway
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - apigateway-network
    ports:
      - 8080:8080

networks:
  apigateway-network:
    name: apigateway-network
    driver: bridge